// <auto-generated />
using System;
using GuildManagerCA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildManagerCA.Infrastructure.Migrations
{
    [DbContext(typeof(GuildManagerDbContext))]
    [Migration("20230914103025_users,roles,specs")]
    partial class usersrolesspecs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildManagerCA.Domain.CharacterAggregate.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CharacterId");

                    b.Property<double>("ItemLevel")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.RaidEventAggregate.RaidEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoAccept")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaidLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RaidEvents", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.RaidLocationAggregate.RaidLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RaidLocations", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.SpecializationAggregate.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SpecializationId");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpecializationRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specializations", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.UserRoleAggregate.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserRoleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("GuildManagerCA.Domain.CharacterAggregate.Character", b =>
                {
                    b.OwnsMany("GuildManagerCA.Domain.RaidEventAggregate.ValueObjects.RaidEventId", "RaidEventIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("RaidEventId");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("CharacterRaidEventIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("GuildManagerCA.Domain.SpecializationAggregate.ValueObjects.SpecializationId", "SpecializationIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SpecializationId");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("CharacterSpecializationIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("RaidEventIds");

                    b.Navigation("SpecializationIds");
                });

            modelBuilder.Entity("GuildManagerCA.Domain.RaidEventAggregate.RaidEvent", b =>
                {
                    b.OwnsMany("GuildManagerCA.Domain.RaidEventAggregate.Entities.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CommentId");

                            b1.Property<Guid>("RaidEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Author")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ModifiedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "RaidEventId");

                            b1.HasIndex("RaidEventId");

                            b1.ToTable("Comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidEventId");
                        });

                    b.OwnsMany("GuildManagerCA.Domain.RaidEventAggregate.Entities.RaidEventAttendance", "Attendances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("RaidEventAttendanceId");

                            b1.Property<Guid>("RaidEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AcceptanceStatus")
                                .HasColumnType("int");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id", "RaidEventId");

                            b1.HasIndex("RaidEventId");

                            b1.ToTable("RaidEventAttendances", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidEventId");
                        });

                    b.Navigation("Attendances");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("GuildManagerCA.Domain.RaidLocationAggregate.RaidLocation", b =>
                {
                    b.OwnsOne("GuildManagerCA.Domain.RaidLocationAggregate.ValueObjects.RaidExpansion", "Expansion", b1 =>
                        {
                            b1.Property<Guid>("RaidLocationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ExpansionImageUrl");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ExpansionName");

                            b1.HasKey("RaidLocationId");

                            b1.ToTable("RaidLocations");

                            b1.WithOwner()
                                .HasForeignKey("RaidLocationId");
                        });

                    b.Navigation("Expansion")
                        .IsRequired();
                });

            modelBuilder.Entity("GuildManagerCA.Domain.SpecializationAggregate.Specialization", b =>
                {
                    b.OwnsOne("GuildManagerCA.Domain.SpecializationAggregate.ValueObjects.CharacterClass", "CharacterClass", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ClassImageUrl");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ClassName");

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.Navigation("CharacterClass")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
